### ISSUE TITLE
Presentation remote window doesn't have a close button

### ISSUE THREAD

**Issue by marmeladapk** [andyholmes/valent#374]
### Current Behavior

Presentation remote window doesn't have a close button

### Expected Behavior

Presentation remote window has a close button

### Desktop

Pantheon

### Operating System

elementary os 7

### Installed from

Nightly Flatpak

### Version

1.0.0.alpha

### Screenshots

![obraz](https://user-images.githubusercontent.com/24512604/221407424-9800b51b-f6a1-4b2c-a2a8-8d01cbf86d26.png)

**Comment by andyholmes** [comment]
Thanks for reporting!

I have a close button on GNOME, but I don't get one on Phosh. I guess Phosh does that because you can swipe-close windows, but that tells me this might be a choice made by the window manager.

I'll have an ask around and see if anyone knows of this behaviour; do you know if elementary has any settings for windows that might affect this?

**Comment by marmeladapk** [comment]
> do you know if elementary has any settings for windows that might affect this?

Nope and I don't use any tweaks that might change default button placement. All other windows have close buttons, sms even has two!

![image](https://user-images.githubusercontent.com/24512604/221436060-deefc9ea-834d-4515-9178-42b1f0cee385.png)

**Comment by andyholmes** [comment]
Ah, I see.

That window uses a custom title bar, so maybe that's what's breaking this. I'll have a look a bit later today and see what I come up with :slightly_smiling_face:
